## Template para empacotamento utilizando o Gitlab-ci.

stages:
    - lint
    - build
    - test
    - deploy

lint_shell:
  stage: lint
  tags:
    - debian-packaging
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install wget locales locales-all -y
    - locale-gen pt_BR.UTF-8
    - export LANG=pt_BR.UTF-8
    - scversion="stable" # or "v0.4.7", or "latest"
    - wget "https://storage.googleapis.com/shellcheck/shellcheck-$scversion.linux.x86_64.tar.xz"
    - tar --xz -xvf "shellcheck-$scversion.linux.x86_64.tar.xz"
    - shellcheck() { "shellcheck-$scversion/shellcheck" "$@"; }
    - ./.linter_shell.sh

build:
  stage: build
  artifacts:
    paths:
      - build/
  tags:
    - debian-packaging
  script:
    - apt-get update && apt-get install -y libx11-dev libcairo2-dev debhelper
    - ./.build.sh

test:
  stage: test
  tags:
    - ubuntu
    - regular
  script:
    - apt-get update && apt-get install -y wget
    # Instalacao previa do lightdm, necessaria devido ao Bug #1537329 do pacote plymouth:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install lightdm language-pack-gnome-pt language-pack-pt-base
    # Instalacao previa de dependencias que dao erros devido a conflitos de pacotes na imagem docker ubuntu:16:04 regular:
    - apt-get install -y xserver-xorg-core-hwe-16.04
    - echo "deb http://repo.c3sl.ufpr.br/le6/ unstable main" > /etc/apt/sources.list.d/le6.list
    - wget -O- http://repo.c3sl.ufpr.br/le6/le.c3sl.ufpr.br.key | apt-key add -
    - echo "Installation test:"
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install $(pwd)/build/*.deb language-pack-gnome-pt language-pack-pt-base
    - echo "Removal test:"
    - pkg_name=$(head -n 1 package/debian/changelog | cut -d' ' -f1)
    - DEBIAN_FRONTEND=noninteractive apt -y remove $pkg_name
  dependencies:
    - build

deploy_for_unstable:
  stage: deploy
  only:
      - develop
  tags:
    - debian-packaging
  script:
    - ./.deploy.sh
  dependencies:
    - build

deploy_for_testing:
  stage: deploy
  only:
      - /^rc-.*$/
  tags:
    - debian-packaging
  script:
    - ./.deploy.sh
  dependencies:
    - build

deploy_for_stable:
  stage: deploy
  when: manual
  only:
      - master
  tags:
    - debian-packaging
  script:
    - ./.deploy.sh
  dependencies:
    - build
