#!/bin/bash

# Copyright (C) 2017 Centro de Computacao Cientifica e Software Livre
# Departamento de Informatica - Universidade Federal do Parana - C3SL/UFPR
#
# This file is part of le-multiterminal
#
# le-multiterminal is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,
# USA.

#### Description: A lightdm cleanup script to prevent undesirable polkitd behavior.
#### Problem: The closure of a lightdm desktop session sometimes does not mean that its
#### respective user logind session is closed as well. This means that one might not be
#### able to log out of a seat despite the closure of his desktop session, screwing with
#### multiseat policies.
#### Workaround: Force the termination of any normal user (non-lightdm) logind session
#### with a "closing" state.
#### Written by: Lucas Sulzbach - ls17@c3sl.ufpr.br on 2018.

while read -r SESSION
do
	STATUS=$(loginctl session-status "${SESSION}" --no-pager | awk '$1~/State/ {print $2}')
	# echo "Session ${SESSION} is ${STATUS}"
	if [[ "${STATUS}" == "closing" ]]; then
		loginctl terminate-session "${SESSION}"
	fi
done < <(loginctl list-sessions | awk '$3!~/lightdm/ && $4~/seat/ {print $1}') 
