#!/bin/bash

# Copyright (C) 2017 Centro de Computacao Cientifica e Software Livre
# Departamento de Informatica - Universidade Federal do Parana - C3SL/UFPR
#
# This file is part of le-multiterminal
#
# le-multiterminal is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,
# USA.

# Script adapted from Laércio de Sousa <laerciosousa@sme-mogidascruzes.sp.gov.br>

index=1
pattern="${1}"
shift

# o lspci do fim do laço (entrada) descobre os barramentos da maquina atual
while read -r line
do
	# substitui : por .
    address=$(echo "${line}" | awk '{ sub(/\./, ":", $1) } { print $1 }')
    echo VIDEO_ADDRESS_${index} = "${address}"

    for xorgconf in "${@}"
    do
	    # atualiza busid no arquivo de configuração conforme o barramento da maquina atual
	    # sub coloca na sintaxe correta do xorg
        awk -v n=${index} -v address="${address}" \
            '$1 == "BusID" {
                if (++count == n) {
                    sub(/[0-9]+:[0-9]+:[0-9]+/, address, $0)
                }
             }
             { print }' "${xorgconf}" > "${xorgconf}.tmp" && mv "${xorgconf}.tmp" "${xorgconf}"
    done

    index=$(( index + 1 ))
done < <(lspci | grep "${pattern}")
