#!/bin/sh
# postinst script for le-multiterminal
#DEBHELPER#
set -e
update-xorg-conf "Silicon.Motion" /etc/X11/xorg.conf.d/98-proinfo-*.conf

if [ ! -f /.dockerenv ]; then
    systemctl daemon-reload
    deb-systemd-helper enable le-multiterminal.service
    # habilita e roda o xorg-daemon
    deb-systemd-helper enable xorg-daemon.socket
    deb-systemd-invoke start xorg-daemon.socket

    udevadm trigger
fi

echo "Por favor reinicie o sistema para o multiterminal ser reconfigurado!"
exit 0
