#!/bin/sh
# postinst script for le-multiterminal
#DEBHELPER#
set -e

update-xorg-conf "Silicon.Motion" /etc/X11/xorg.conf.d/98-proinfo-*.conf

systemctl daemon-reload
deb-systemctl-helper enable le-multiterminal

# habilita e roda o xorg-daemon
deb-systemctl-helper enable xorg-daemon.socket
deb-systemctl-invoke start xorg-daemon.socket

udevadm trigger

echo "Por favor reinicie o sistema para o multiterminal ser reconfigurado!"
exit 0
